services:
  frontend:
    build:
      context: . # Root directory
      dockerfile: ./src/client/Dockerfile
    image: guardql-frontend:latest
    ports:
      - "8081:80"
    env_file:
      - .env

  backend:
    build:
      context: . # Root directory
      dockerfile: ./src/server/Dockerfile
    image: guardql-backend:latest
    ports:
      - "4000:4000"
    environment:
      JWT_SECRET: ${JWT_SECRET}
      DATABASE_URL: ${DATABASE_URL}
    env_file:
      - .env