# This docker compose file is necessary to run both Dockerfiles;
# Run `docker compose build` to trigger the dockerfile build
# Once successful, create the containers using `docker compose up`
# To turn off and remove containers, use `docker compose down`
# UPDATE: This file is no longer needed since I had to manually use docker run commands for both local machine and virtual instance
services:
  frontend:
    build:
      context: . # Root directory
      dockerfile: Dockerfile.frontend
      args:
        platform: amd64
    image: guardql-frontend:latest # name of the frontend docker image
    ports:
      - '8081:80' # frontend port
    env_file:
      - .env

  backend:
    build:
      context: . # Root directory
      dockerfile: Dockerfile.backend
      args:
        platform: amd64
    image: guardql-backend:latest # name of the backend docker image
    ports:
      - '4000:4000' # apollo server port
    environment:
      JWT_SECRET: ${JWT_SECRET}
      DATABASE_URL: ${DATABASE_URL}
    env_file:
      - .env
